services:

  backend1:
    build: ./server
    container_name: backend1

  backend2:
    build: ./server
    container_name: backend2

  backend3:
    build: ./server
    container_name: backend3

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3